#skUtilities

#--------------------------------------------------------------------------

#Should this addon check for an update every 12 hours

checkForUpdates: true
downloadUpdates: false

#--------------------------------------------------------------------------

#If set to 'true' (UnSafe Option) anything using paths in this addon (files)
#will start looking in the root directory of your whole server!
#Example: Paths would start at 'root' or if your using windows 'c:/'

useRootAsDefaultPath: false

#If set to 'false' (Safe Option) anything using paths in this addon (files)
#will start looking in the root directory of the minecraft server!
#Example: Paths would start at 'MinecraftServerRootFolder'

#--------------------------------------------------------------------------

#Disables or Enables parts of the addon.
#If disabled the only way to renable is to change to true and restart the server,
#this only disables/enables those parts when you start the server.

loadConversions: true
loadFiles: true
loadUtilities: true

#--------------------------------------------------------------------------

#DO NOT CHANGE THIS!
configVersion: 3
