name: skUtilities
description: An addon for skript that adds conversions, utilities, files and much more.
author: tim740
website: https://tim740.github.io/
main: uk.tim740.skUtilities.skUtilities
version: 0.7.3
depend: [Skript]